name: Terraform Plan on PR
on:
  pull_request:
    branches: [ main ]
env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VERSION: '1.5.0'
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # For commenting plan output
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var-file=environments/dev.tfvars -detailed-exitcode -out=tfplan
        if [ $? -eq 2 ]; then
          echo "Plan detected changes; summary below:"
          terraform show -json tfplan > plan.json
          echo "plan changed=true" >> $GITHUB_OUTPUT
        fi
    - name: IaC Security Scan (Checkov)
      if: steps.plan.outputs.plan != 'false'
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ./terraform/
        framework: terraform
    - name: Comment Plan on PR
      if: steps.plan.outputs.plan == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const planOutput = fs.readFileSync('plan.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### Terraform Plan\n\`\`\`hcl\n${planOutput}\n\`\`\``
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}